In [2]:
import numpy as np

In [6]:
arr=np.arange(0,17)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [7]:
arr[7]

7

In [8]:
arr[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
arr_2d = np.array(([3,6,9],[10,15,20],[20,25,30],[90,67,56]))
arr_2d

array([[ 3,  6,  9],
       [10, 15, 20],
       [20, 25, 30],
       [90, 67, 56]])

In [11]:
arr_2d[2]

array([20, 25, 30])

In [36]:
arr_2d[2][2]

30

In [13]:
arr_2d[2,1]

25

In [22]:
arr_2d[2:3,1:]

array([[25, 30]])

In [15]:
arr_2d[2:4]

array([[20, 25, 30],
       [90, 67, 56]])

In [24]:
arr_2d[:2][:1]

array([[3, 6, 9]])

In [25]:
arr_2d[2:4,1:2]

array([[25],
       [67]])

In [26]:
arr_2d

array([[ 3,  6,  9],
       [10, 15, 20],
       [20, 25, 30],
       [90, 67, 56]])

In [34]:
arr_2d[2:4][0:1]

array([[20, 25, 30]])

In [35]:
arr_2d[2:4][1:2]

array([[90, 67, 56]])

In [37]:
arr_2d>10

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [38]:
arr_2d[arr_2d>10]

array([15, 20, 20, 25, 30, 90, 67, 56])

In [42]:
arr_2d[arr_2d==20]

array([20, 20])

In [43]:
np.where(arr_2d>10)

(array([1, 1, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [44]:
arr_2d[np.where(arr_2d>10)]

array([15, 20, 20, 25, 30, 90, 67, 56])

In [52]:
np.where(arr_2d>10,arr1,2)

array([[2, 2, 2],
       [2, 4, 8],
       [0, 9, 2],
       [1, 8, 5]])

In [51]:
arr1=np.array([5,7,6,2,4,8,0,9,2,1,8,5]).reshape(4,3)